version: "3.8"
services: 
  nuxt:
    image: nuxt
    build: 
      context: ./
      dockerfile: Dockerfile
    container_name: nuxt
    ports:
      - 3000:8080
    volumes:
      - ./:/app
    




