version: "3.5"
services:
  client:
    image: client_container
    container_name: client-container
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    ports:
      - 8080:8080
    environment: 
      - CHOKIDAR_USEPOLLING=true  


  json-server:
    image: server_container
    container_name: json-server-container
    build: 
      context: ./db
      dockerfile: Dockerfile.prod
    ports: 
      - 3000:3000 
    volumes: 
      - ./db/db.json:/data/db.json
    command: json-server --watch /data/db.json --host 0.0.0.0  
    environment: 
      - CHOKIDAR_USEPOLLING=true      

    
  